"""audit_missing_fields

Revision ID: 2323898380cc
Revises: 237140312085
Create Date: 2026-02-12 07:23:59.500441
"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '2323898380cc'
down_revision: Union[str, None] = '237140312085'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('last_message_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('conversations', sa.Column('message_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('leads', sa.Column('source_channel', sa.String(length=20), nullable=True))
    op.add_column('leads', sa.Column('is_after_hours', sa.Boolean(), nullable=True))
    op.add_column('properties', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('properties', sa.Column('slug', sa.String(length=255), nullable=True))
    op.add_column('properties', sa.Column('timezone', sa.String(length=50), server_default='Asia/Kuala_Lumpur', nullable=False))
    op.add_column('properties', sa.Column('plan_tier', sa.String(length=20), server_default='pilot', nullable=False))
    op.add_column('properties', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.create_unique_constraint(None, 'properties', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'properties', type_='unique')
    op.drop_column('properties', 'is_active')
    op.drop_column('properties', 'plan_tier')
    op.drop_column('properties', 'timezone')
    op.drop_column('properties', 'slug')
    op.drop_column('properties', 'updated_at')
    op.drop_column('leads', 'is_after_hours')
    op.drop_column('leads', 'source_channel')
    op.drop_column('conversations', 'message_count')
    op.drop_column('conversations', 'last_message_at')
    # ### end Alembic commands ###
