"""add_notification_email

Revision ID: 237140312085
Revises: 
Create Date: 2026-02-10 19:30:03.848773
"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import pgvector

# revision identifiers
revision: str = '237140312085'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('whatsapp_number', sa.String(length=20), nullable=True),
    sa.Column('notification_email', sa.String(length=255), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('operating_hours', sa.JSON(), nullable=True),
    sa.Column('knowledge_base_config', sa.JSON(), nullable=True),
    sa.Column('adr', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ota_commission_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analytics_daily',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('total_inquiries', sa.Integer(), nullable=False),
    sa.Column('after_hours_inquiries', sa.Integer(), nullable=False),
    sa.Column('after_hours_responded', sa.Integer(), nullable=False),
    sa.Column('leads_captured', sa.Integer(), nullable=False),
    sa.Column('handoffs', sa.Integer(), nullable=False),
    sa.Column('avg_response_time_sec', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('estimated_revenue_recovered', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('channel_breakdown', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_analytics_property_date', 'analytics_daily', ['property_id', 'report_date'], unique=True)
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('guest_identifier', sa.String(length=255), nullable=True),
    sa.Column('guest_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_after_hours', sa.Boolean(), nullable=False),
    sa.Column('ai_mode', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conversations_guest', 'conversations', ['property_id', 'guest_identifier'], unique=False)
    op.create_index('ix_conversations_property_after_hours', 'conversations', ['property_id', 'is_after_hours'], unique=False)
    op.create_index('ix_conversations_property_status', 'conversations', ['property_id', 'status'], unique=False)
    op.create_table('kb_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('doc_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_kb_property_type', 'kb_documents', ['property_id', 'doc_type'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('guest_name', sa.String(length=255), nullable=True),
    sa.Column('guest_phone', sa.String(length=20), nullable=True),
    sa.Column('guest_email', sa.String(length=255), nullable=True),
    sa.Column('intent', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('estimated_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_leads_property_date', 'leads', ['property_id', 'captured_at'], unique=False)
    op.create_index('ix_leads_property_status', 'leads', ['property_id', 'status'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_conversation', 'messages', ['conversation_id', 'sent_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messages_conversation', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_leads_property_status', table_name='leads')
    op.drop_index('ix_leads_property_date', table_name='leads')
    op.drop_table('leads')
    op.drop_index('ix_kb_property_type', table_name='kb_documents')
    op.drop_table('kb_documents')
    op.drop_index('ix_conversations_property_status', table_name='conversations')
    op.drop_index('ix_conversations_property_after_hours', table_name='conversations')
    op.drop_index('ix_conversations_guest', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index('ix_analytics_property_date', table_name='analytics_daily')
    op.drop_table('analytics_daily')
    op.drop_table('properties')
    # ### end Alembic commands ###
